### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by remi-daigle** [remi-daigle/MarxanConnect#57]
#### Description
After a few attempts, we have not been able to compile a Linux compatible version. The app itself should be compatible with Linux since we ironed out the file path issues for the macOS version. The main obstacle at this point is installing the right python packages/modules.  Currently I am stuck on finding a compatible version of `fiona`

#### To Reproduce
Install the latest Anaconda (or with python 3.6) and then in a linux terminal run:
```
conda create --name marcon -c conda-forge wxpython matplotlib geopandas descartes shapely pandas numpy basemap basemap-data-hires fiona
conda activate marcon
python -c 'import fiona'
```
and the output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/remi/anaconda3/envs/marcon/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/remi/anaconda3/envs/marcon/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /home/remi/anaconda3/envs/marcon/lib/python3.7/site-packages/fiona/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs

```

Something seems incompatible between `libgdal` and `fiona`, but I don't know how to fix this!

**Comment by carlostighe** [comment]
seems to be related to this - https://github.com/conda-forge/fiona-feedstock/issues/68

**Comment by remi-daigle** [comment]
Thanks @carlostighe it seems like they closed that issue, do you know if it's actually resolved? I don't have access to a linux machine during self-isolation because of COVID-19, so I won't be able to check in the near future. Please let me know if you have any success building the app for linux.

**Comment by carlostighe** [comment]
I dont know if its resolved. 
I dont use anaconda so have been unable to have a look at it. 
If I get the chance Ill look into it
