### ISSUE TITLE
Error while Generating Connectivity Matrix

### ISSUE THREAD

**Issue by chrismallon** [remi-daigle/MarxanConnect#81]
#### Description
While using the Marxan Connect GUI (1.0.0) on my windows 10 PC, errors are raised when using the 'Generate Connectivity Matrix' button on tab 2 (Connectivity Input).  The error was raised while replicating the tutorial workflow, using tutorial data. When using the supplied connectivity matrix (IsolationByDistance.csv) I can complete the workflow, but I cannot reproduce the IsolationByDistance file.

#### Screenshots
![image](https://user-images.githubusercontent.com/15743083/83452540-237f4300-a416-11ea-9f2c-1ec6bfdce157.png)
![image](https://user-images.githubusercontent.com/15743083/83452551-27ab6080-a416-11ea-9a94-2380e1fdd283.png)

#### Debug Log
C:\Program Files (x86)\MarxanConnect
Warning: Spatial files will be transformed to an equal-area projection (+proj=laea +lat_0=-16.436659514925836 +lon_0=146.04184868318862 +ellps=WGS84) for most spatial analyses
Warning: Spatial files will be transformed to an equal-area projection (+proj=laea +lat_0=-16.436659514925836 +lon_0=146.04184868318862 +ellps=WGS84) for most spatial analyses
Warning: Spatial files will be transformed to an equal-distance projection (+proj=eqdc +lat_1=-19.89656232173732 +lat_2=-12.976756708114351 +lon_0=146.04184868318862 +ellps=WGS84) for this spatial analyses
Warning: Error in habitatresistance2conmats
Traceback (most recent call last):
  File "MarxanConnectGUI.py", line 1674, in on_land_generate_button
  File "site-packages\marxanconpy\spatial.py", line 296, in habitatresistance2conmats
  File "site-packages\geopandas\geodataframe.py", line 443, in to_crs
  File "site-packages\geopandas\geoseries.py", line 304, in to_crs
  File "site-packages\pyproj\__init__.py", line 362, in __new__
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'no arguments in initialization list'

#### Files
bioregion_short.shp, hex_planning_units.shp

#### To Reproduce
You can reproduce the error through the GUI screenshots above.

**Comment by chrismallon** [comment]
Note: I also got the same error when providing a path and filename for the new connectivity matrix.
![image](https://user-images.githubusercontent.com/15743083/83463063-2edc6980-a42a-11ea-8a12-565af48e5f23.png)

**Comment by remi-daigle** [comment]
Hey @goose0058 
I'm so sorry, github didn't notify me about these issues!
I will have a look later this week! I assume this is still an issue?
